# Psychoinformatics - Week 9 (Exercises)
by yourname (your email)

In [7]:
import numpy as np
from sklearn import *
from matplotlib.pyplot  import *
%matplotlib inline

## 1 檢查 machine learning pipeline (6 points)

### 1.1 請打亂原本的Y觀察正確率是否和chance level (0.33)有差異? 若有, why? (3 points)

In [37]:
# 本題在研究打亂X和打亂Y有差別嗎?
iris = datasets.load_iris()
X=iris.data
Y=iris.target
print(Y)
print(X)
clf=neighbors.KNeighborsClassifier(1)
clf.fit(X,Y)
accuracy=np.mean(clf.predict(X)==Y)
print(accuracy)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 

In [38]:
np.random.shuffle(Y)
print(Y)
print(X)
clf=neighbors.KNeighborsClassifier(1)
kf=cross_validation.KFold(len(Y),10,shuffle=True)
sc=cross_validation.cross_val_score(clf,X,Y,cv=kf)
print(sc.mean())

[0 1 0 0 0 1 0 2 0 2 0 1 1 1 0 1 2 1 0 0 2 1 2 1 2 1 1 1 1 2 1 2 0 0 2 2 1
 0 1 2 2 2 2 0 2 2 2 2 0 0 0 2 0 2 2 2 0 0 0 0 1 1 1 1 2 2 2 0 2 2 2 2 2 1
 1 1 2 2 2 2 0 0 2 1 0 2 1 0 1 0 2 1 1 0 0 1 0 1 0 0 1 2 0 1 0 0 1 0 2 2 2
 2 1 0 1 2 1 2 1 0 2 0 1 1 1 0 0 0 2 2 1 0 1 0 0 1 0 2 1 1 2 1 0 1 0 1 1 2
 0 1]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 

### 1.2 請用統計檢定accuracies中的結果是否和chance level (0.5)有差異? 若有, why? (3 points)

In [56]:
Y=np.remainder(range(200),2) 
print(Y)#Y的0和1個數一樣多
print(len(Y))

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
200


In [71]:
# 跑一百次測試:
clf=svm.SVC()
accuracies=[]
for i in range(100): 
 X=np.random.rand(200,2) # X取亂數
 kf=cross_validation.KFold(len(Y),len(Y),shuffle=True) # Leave-one-out cross-validation
 sc=cross_validation.cross_val_score(clf,X,Y,cv=kf)
 accuracies.append(sc.mean())

In [72]:
# Please do your statistical tests here:
print(sum(accuracies)/len(accuracies))
print(accuracies)

0.3908999999999998
[0.26, 0.505, 0.42, 0.535, 0.53, 0.0, 0.53, 0.485, 0.515, 0.0, 0.225, 0.495, 0.49, 0.565, 0.525, 0.485, 0.52, 0.51, 0.39, 0.0, 0.455, 0.0, 0.43, 0.405, 0.26, 0.44, 0.0, 0.29, 0.0, 0.475, 0.51, 0.49, 0.0, 0.455, 0.0, 0.515, 0.535, 0.425, 0.51, 0.155, 0.0, 0.51, 0.525, 0.585, 0.345, 0.44, 0.0, 0.435, 0.535, 0.0, 0.49, 0.13, 0.0, 0.0, 0.46, 0.47, 0.53, 0.45, 0.45, 0.485, 0.525, 0.47, 0.0, 0.535, 0.41, 0.53, 0.5, 0.455, 0.47, 0.57, 0.54, 0.515, 0.46, 0.515, 0.545, 0.54, 0.0, 0.54, 0.465, 0.39, 0.56, 0.0, 0.515, 0.525, 0.0, 0.49, 0.46, 0.46, 0.54, 0.43, 0.53, 0.525, 0.475, 0.44, 0.475, 0.53, 0.495, 0.535, 0.475, 0.48]


Please write your discussion here, if any.

### Please submit this file to http://hpc.psy.ntu.edu.tw/info before noon next Wednesday.